### ISSUE TITLE
GeneMarkS-T missing from rnaQUAST docker

### ISSUE THREAD

**Issue by giulippa** [ablab/rnaquast#11]
Hello,
I'm having trouble running rnaQUAST as docker or singularity as GeneMarkS-T is not installed in the container and there is no way to turn off the usage of this software when running rnaQUAST.py, it will search for GeneMarkS-T automatically even without specifying with the --gene_mark
The command looks like this (I've run it with the debug flag):
`singularity run rnaquast_2.2.1--h9ee0642_0.sif rnaQUAST.py -o rnaquast -c transcripts.fasta -1 CL_R1_trimmed.fastq.gz -2 CL_R2_trimmed.fastq.gz -s CL_unpaired.fastq.gz -ss --blat -d`

And this is the log file:
```
rnaQUAST: 2.2.1

System information:
  OS: Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-glibc2.28 (linux_64)
  Python version: 3.9.7
  CPUs number: 48

External tools:
  matplotlib: 3.4.3
  joblib: 1.1.0
  gffutils: 0.10.1
  blastn: 2.12.0+
  makeblastdb: 2.12.0+
  blat: 36

Started: 2021-11-15 16:27:42

Logging to rnaquast/logs/rnaQUAST.log

NOTICE: Maximum number of threads is set to 16 (use --threads option to set it manually)
Using strand specific transcripts...

  2021-11-15 16:27:42
  Getting transcripts from transcripts.fasta...
  Done.

2021-11-15 16:27:57
Transcripts:
  transcripts.fasta -> transcripts


Processing transcripts from transcripts.fasta:

  2021-11-15 16:27:57
  Getting BASIC TRANSCRIPTS metrics...
  Done.
  Getting SENSITIVITY metrics...

2021-11-15 16:27:59
  Running GeneMarkS-T (Gene Prediction in Transcripts)...

[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/rnaQUAST.py", line 348, in <module>
    return_code = main_utils()
  File "/usr/local/bin/rnaQUAST.py", line 305, in main_utils
    transcripts_metrics[i_transcripts].get_transcripts_metrics\
  File "/usr/local/share/rnaquast-2.2.1-0/metrics/TranscriptsMetrics.py", line 79, in get_transcripts_metrics
    self.assembly_completeness_metrics. \
  File "/usr/local/share/rnaquast-2.2.1-0/metrics/AssemblyCompletenessMetrics.py", line 376, in get_assembly_completeness_metrics
    GeneMarkS_TMetrics.get_GeneMarkS_T_metrics(type_organism, threads, args.strand_specific,
  File "/usr/local/share/rnaquast-2.2.1-0/metrics/AssemblyCompletenessMetrics.py", line 227, in get_GeneMarkS_T_metrics
    GeneMarkS_TMetrics.get_GeneMarkS_T_report(type_organism, args_threads, args_ss, transcripts_path, tmp_dir,
  File "/usr/local/share/rnaquast-2.2.1-0/metrics/AssemblyCompletenessMetrics.py", line 244, in get_GeneMarkS_T_report
    initial_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

ERROR! Exception caught!

In case you have troubles running rnaQUAST, you can write to rnaquast_support@ablab.spbau.ru
Please provide us with rnaQUAST.log file from the output directory.
```

**Comment by andrewprzh** [comment]
Dear Giulia,

Yes, when the reference is not available rnaQUAST uses GeneMark for annotation. With current version there is no workaround, you will need to download GeneMark and add it to the PATH variable. I guess it can be downloaded here http://topaz.gatech.edu/GeneMark/license_download.cgi

You may try to provide some related genome and annotation so that GeneMark will not be used and further ignore refrence-based output. We'll try to add an option for that in the next release.

Also, I suggest not to use --blat option since gmap show far better results.

Best
Andrey

**Comment by andrewprzh** [comment]
I tried to reproduce you error, and it seems that the problem is not with GeneMarkS-T. When GeneMark is not available rnaQUAST still works fine, just gives and error message.

Your log reads:
    initial_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

This is quite odd, since this line just asks for a current working directory. There clearly is a problem with singularity, not with rnaQUAST.

Best
Andrey
